#Copy to api_keys.properties with proper info
#JIRA A23Keys
#OrganizationId:b46e18ee-e5c9-4fec-8b9f-fd5e78f86caf
#APIKey:ATCTT3xFfGN0n620bzWYkQ0_LFSkPIL80RPZ4k3LgiPHxDIvx3EA6eQDSuiUDc2TFqaUzfTRgmE55uNatlrLTPtNM0L0E8u6G1bq4gJts-taZg_yeR9QHxtYzm-179UMkYlKiEhH6oYPeWlJoqpiftJpCXBvC9v2GsJFEn94pEwIbnmI0Efdgss=C34FDE09
#APiKey2:ATATT3xFfGF0bq21EV8byjKTCt_wgCDsVmRgf9_1f4V4r-spsr2KBI2iu2aP1JhYOOBgkD7XMYw8rqeA5C-Aml2yKVvUFrKp_Sm-rbjcAgJo4tODYJiAEgT2mVfQ3W6Z3LdOC7XkELmAR2kBgZK1e_42qXT30jrRLfJv3L3cXSgFYyHVMgGwSPI=DB4AF355


eq1.email=lacouf@gmail.com
eq1.apitoken=ATATT3xFfGF0bq21EV8byjKTCt_wgCDsVmRgf9_1f4V4r-spsr2KBI2iu2aP1JhYOOBgkD7XMYw8rqeA5C-Aml2yKVvUFrKp_Sm-rbjcAgJo4tODYJiAEgT2mVfQ3W6Z3LdOC7XkELmAR2kBgZK1e_42qXT30jrRLfJv3L3cXSgFYyHVMgGwSPI=DB4AF355
eq1.url=https://420-565-a23.atlassian.net
